version: '3.8'

services:

  app:
    image: polet-app:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: polet-app-prod
    ports:
      - "3003:3003"
    depends_on:
      redis:
        condition: service_healthy
      mongo1:
        condition: service_healthy
      admin-init:
        condition: service_completed_successfully
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - uploads_data:/app/uploads
      - logs_data:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  worker:
    image: polet-worker:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: polet-worker-prod
    depends_on:
      redis:
        condition: service_healthy
      mongo1:
        condition: service_healthy
      admin-init:
        condition: service_completed_successfully
    env_file:
      - .env
    networks:
      - backend
    command: ["node", "dist/src/queues/worker/processors.js"]
    volumes:
      - uploads_data:/app/uploads
      - logs_data:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]  # если есть
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s

  redis:
    image: redis:7-alpine
    container_name: polet-redis-prod
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    command: redis-server --appendonly yes

  mongo1:
    image: mongo:6.0
    container_name: mongo1-prod
    ports:
      - "27017:27017"
    volumes:
      - mongo1_data:/data/db
    command: mongod --replSet rs0 --bind_ip_all
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - backend
    restart: unless-stopped

  mongo2:
    image: mongo:6.0
    container_name: mongo2-prod
    ports:
      - "27018:27017"
    volumes:
      - mongo2_data:/data/db
    command: mongod --replSet rs0 --bind_ip_all
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - backend
    restart: unless-stopped

  mongo3:
    image: mongo:6.0
    container_name: mongo3-prod
    ports:
      - "27019:27017"
    volumes:
      - mongo3_data:/data/db
    command: mongod --replSet rs0 --bind_ip_all
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - backend
    restart: unless-stopped

  rs-rs-init:
    image: polet-rs-init:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: polet-rs-init-prod
    depends_on:
      mongo1: { condition: service_healthy }
      mongo2: { condition: service_healthy }
      mongo3: { condition: service_healthy }
    networks:
      - backend
    command: sh -c "node dist/src/scripts/init-replica.js"
    healthcheck:
      disable: true
  admin-init:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: polet-admin-init-prod
    depends_on:
      rs-init:
        condition: service_completed_successfully
    command: ["node", "dist/src/scripts/createAdmin.js"]
    restart: "on-failure"
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - ./src/scripts:/app/src/scripts

networks:
  backend:

volumes:
  redis_data:
  mongo1_data:
  mongo2_data:
  mongo3_data:
  uploads_data:
  logs_data:
