FROM node:20

# Устанавливаем зависимости для нативных модулей
RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3003

# Будет переопределён в docker-compose через command
CMD ["npm", "run", "dev"]