// config/routes.config.ts
import type { Application } from "express";
import bullBoardMiddleware from "../src/queues/bullBoard.js";
import authRoutes from "../src/routes/authRoutes.js";
import bannerRoutes from "../src/routes/bannerRoutes.js";
import bannerStatsRoutes from "../src/routes/bannerStatsRoutes.js";
import cartRoutes from "../src/routes/cartRoutes.js";
import categoriesRoutes from "../src/routes/categoriesRoutes.js";
import companyRoutes from "../src/routes/companyRoutes.js";
import consentRoutes from "../src/routes/consentRoutes.js";
import contactsRoutes from "../src/routes/contactsRoutes.js";
import contentBlockRoutes from "../src/routes/contentBlockRoutes.js";
import deliveryRoutes from "../src/routes/deliveryRoutes.js";
import discountRoutes from "../src/routes/discountRoutes.js";
import faqRoutes from "../src/routes/faqRoutes.js";
import feedRoutes from "../src/routes/feed.routes.js";
import feedbackRoutes from "../src/routes/feedbackRoutes.js";
import filesRoutes from "../src/routes/filesRoutes.js";
import healthRoutes from "../src/routes/healthcheckRoutes.js";
import notificationsRoutes from "../src/routes/notificationsRoutes.js";
import ordersRoutes from "../src/routes/ordersRoutes.js";
import productsRoutes from "../src/routes/productsRoutes.js";
import refundRoutes from "../src/routes/refundRoutes.js";
import reviewsRoutes from "../src/routes/reviewsRoutes.js";
import searchRoutes from "../src/routes/searchRoutes.js";
import sitemapRoutes from "../src/routes/sitemapRoutes.js";
import topicRoutes from "../src/routes/topicRoutes.js";
import usersRoutes from "../src/routes/usersRoutes.js";
import wishlistRoutes from "../src/routes/wishlistRoutes.js";
export default (app: Application): void => {
  app.use("/auth", authRoutes);
  app.use("/health", healthRoutes);
  app.use("/consent", consentRoutes);
  app.use("/feed", feedRoutes);
  app.use("/contacts", contactsRoutes);
  app.use("/notifications", notificationsRoutes);
  app.use("/feedback", feedbackRoutes);
  app.use("/topics", topicRoutes);
  app.use("/files", filesRoutes);
  app.use("/categories", categoriesRoutes);
  app.use("/products", productsRoutes);
  app.use("/search", searchRoutes);
  app.use("/reviews", reviewsRoutes);
  app.use("/company", companyRoutes);
  app.use("/faq", faqRoutes);
  app.use("/bannerStats", bannerStatsRoutes);
  app.use("/refund", refundRoutes);
  app.use("/sitemap", sitemapRoutes);
  app.use("/content-blocks", contentBlockRoutes);
  app.use("/users", usersRoutes);
  app.use("/banners", bannerRoutes);
  app.use("/delivery", deliveryRoutes);
  app.use("/discounts", discountRoutes);
  app.use("/orders", ordersRoutes);
  app.use("/cart", cartRoutes);
  app.use("/wishlist", wishlistRoutes);
  app.use("/admin/queues", bullBoardMiddleware);
};
